### ISSUE TITLE
length error!

### ISSUE THREAD

**Issue by narjesgoshtasbi** [SharifAmit/RVGAN#21]
Hi, I got this error running train.py using DRIVE dataset in Colab:

Traceback (most recent call last):
  File "/content/drive/MyDrive/RVGAN-master/train.py", line 215, in <module>
    train(d_model1, d_model2,g_model_coarse, g_model_fine, rvgan_model, dataset, n_epochs=args.epochs, n_batch=args.batch_size, n_patch=[128,64],savedir=args.savedir)
  File "/content/drive/MyDrive/RVGAN-master/train.py", line 100, in train
    g_global_loss,_ = g_global_model.train_on_batch([X_realA_half,X_realB_half], [X_realC_half])

ValueError: The two structures don't have the same sequence length. Input structure has length 1, while shallow structure has length 2.

Would you help me to fix it?

**Comment by manjithadulana98** [comment]
I have also stuck with the same error @nargesgoshtasbi did you got a solution

**Comment by SharifAmit** [comment]
Hi,

The current master branch is for tf 2.0 which the colab does not support. And to re create our results you would need to install this version in a local vm or cluster which supports tf 2.0. Please go through the readme.MD again.


You can try the branch with the tf 2.6 version in colab. This will require you to uninstall any tf versions in colab and re install tf 2.6 afterwards.

https://github.com/SharifAmit/RVGAN/tree/tf-2.6

However, tf 2.6 is an experimental version and we did not train or test our models on this so there might be stability issues in results.

Thanks

**Comment by narjesgoshtasbi** [comment]
Hi. It seems that Colab does not support tf==2.6 too! 
I should try the project when have access to another gpu server! Please let me know if other solutions exist. 
Thank you.
